# Project information
site_name: Zabbix Book
site_url: https://thezabbixbook.com/
site_author: The Monitoring Penmasters
site_description: "A free, community driven online resource to master Zabbix: built to give back, sustain the community, and help you become truly empowered with monitoring."
copyright: Copyright &copy; 2025 Stichting The Monitoring Penmasters

# Repository
repo_name: penmasters
repo_url: https://github.com/penmasters/zabbix-book
edit_uri: edit/main/docs
docs_dir: docs

# Navigation
nav:
  - Welcome: index.md
  - Guidelines: Guidelines.md
  - Supporters and contributors: Supporters-Contributors.md
  - Getting started:
      - Initial steps: ch00-getting-started/initial-steps.md
      - System Requirements: ch00-getting-started/Requirements.md
  - "Chapter 01 : Zabbix components":
      - Zabbix components: ch01-zabbix-components/chapter.md
      - Basic Installation: ch01-zabbix-components/basic-installation.md
      - HA Setup: ch01-zabbix-components/ha-setup.md
  - "Chapter 02 : Installation":
      - ch02-zabbix-installation/chapter.md
      - ch02-zabbix-installation/frontend.md
      - ch02-zabbix-installation/host-groups.md
      - ch02-zabbix-installation/user-groups.md
      - "External Authentication":
          - ch02-zabbix-installation/http.md
          - ch02-zabbix-installation/ldap-ad.md
          - ch02-zabbix-installation/saml.md
          - ch02-zabbix-installation/mfa.md
  - "Chapter 03 : Proxies and Webcomponents":
      - ch03-zabbix-proxies/chapter.md
      - ch03-zabbix-proxies/proxy-basics.md
      - ch03-zabbix-proxies/active-passive-proxies.md
      - ch03-zabbix-proxies/proxies-as-container.md
      - ch03-zabbix-proxies/proxy-groups.md
      - ch03-zabbix-proxies/web-services.md
  - "Chapter 04 : Collecting data ":
      - ch04-zabbix-collecting-data/chapter.md
      - ch04-zabbix-collecting-data/dataflow.md
      - ch04-zabbix-collecting-data/hosts.md
      - ch04-zabbix-collecting-data/simple-checks.md
      - ch04-zabbix-collecting-data/host-interfaces.md
      - ch04-zabbix-collecting-data/zabbix-agent-passive.md
      - ch04-zabbix-collecting-data/zabbix-agent-active.md
      - ch04-zabbix-collecting-data/snmp-polling.md
      - ch04-zabbix-collecting-data/preprocessing.md
      - ch04-zabbix-collecting-data/dependent.md
      - ch04-zabbix-collecting-data/snmp-trapping.md
      - ch04-zabbix-collecting-data/ssh-telnet.md
      - ch04-zabbix-collecting-data/http.md
      - ch04-zabbix-collecting-data/script.md
      - ch04-zabbix-collecting-data/jmx.md
      - ch04-zabbix-collecting-data/ipmi.md
      - ch04-zabbix-collecting-data/database-odbc.md
      - ch04-zabbix-collecting-data/database-agent.md
      - ch04-zabbix-collecting-data/zabbix-trapper.md
      - ch04-zabbix-collecting-data/external-checks.md
      - ch04-zabbix-collecting-data/browser.md
      - ch04-zabbix-collecting-data/calculated.md
      - ch04-zabbix-collecting-data/zabbix-internal.md
  - "Chapter 05 : Triggers":
      - ch05-zabbix-triggers/chapter.md
      - ch05-zabbix-triggers/triggers.md
      - ch05-zabbix-triggers/advanced-triggers.md
  - "Chapter 06 : Templates":
      - ch06-zabbix-templates/chapter.md
  - "Chapter 07 : Alerting":
      - ch07-zabbix-alerts/chapter.md
      - ch07-zabbix-alerts/media-types.md
      - ch07-zabbix-alerts/scripts.md
      - ch07-zabbix-alerts/maintenance.md
      - ch07-zabbix-alerts/actions.md
  - "Chapter 08 : LLD":
      - ch08-zabbix-lld/chapter.md
      - Custom LLD: ch08-zabbix-lld/custom.md
      - Dependent LLD: ch08-zabbix-lld/lld-with-dependent-items.md
  - "Chapter 09 : Extending Zabbix":
      - ch09-zabbix-extending/chapter.md
      - ch09-zabbix-extending/scripts.md
  - "Chapter 10 : Discovery":
      - ch10-zabbix-discovery/chapter.md
  - "Chapter 11 : Visualisation":
      - ch11-zabbix-visualisation/chapter.md
  - "Chapter 12 : Zabbix API":
      - ch12-zabbix-api/chapter.md
  - "Chapter 13 : Advanced set up and security":
      - ch13-advanced-security/chapter.md
      - SELinux: ch13-advanced-security/selinux-zabbix.md
      - Securing the frontend: ch13-advanced-security/securing-frontend.md
      - Securing the agent: ch13-advanced-security/agent-security.md
      - Storing secrets: ch13-advanced-security/using-vault.md
      - Partitioning MariaDB: ch13-advanced-security/partitioning-database.md
      - Partitioning PostgreSQL with TimescaleDB: ch13-advanced-security/partitioning-postgresql-database.md
  - "Chapter 14 : Real world examples":
      - ch14-zabbix-real-world-examples/chapter.md

theme:
  language: en
  name: material
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Nunito
  icon:
    logo: material/library
  features:
    #    - content.code.select #seems to be not working for some reason
    #    - navigation.tabs #add navigation to the top
    - navigation.expand
    - navigation.prune
    - navigation.path
    #    - navigation.sections # removes the collapsable menu
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.view
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/linewrap.css

# Plugins
plugins:
  - mermaid2
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - fr
        - de
        - it
        - nl
        - pt
        - es
        - th
        - zh
        - ru
        - en
  - autolinks
  - privacy #GDPR compliance
  - spellcheck:
      backends: # the backends you want to use
        - symspellpy # as strings
        - codespell: # or nested configs
            dictionaries: [clear, rare]

      # known_words can also be a list of words
      known_words: known_words.txt

      # ignore words in <code> tags
      ignore_code: yes

      # minimum length of words to consider
      min_length: 2

      # maximum number of capital letters in a word
      max_capital: 1

      # keep unicode characters
      allow_unicode: no

      # skip files entirely (supports Unix shell-style wildcards)
      skip_files:
        - fr/*
        - de/*
        - it/*
        - nl/*
        - pt/*
        - es/*
        - th/*
        - zh/*
        - ru/*
        - Guidelines.*.md
      # - credits.md
      #- coverage.md
      #- reference/*

      # whether to only check in strict mode
      strict_only: no

  - i18n:
      reconfigure_material: true
      fallback_to_default: true
      docs_structure: folder
      languages:
        - locale: fr
          name: Français
          build: true
        - locale: de
          name: German
          build: true
        - locale: it
          name: Italian
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: pt
          name: Portuguese
          build: true
        - locale: es
          name: Spanish
          build: true
        - locale: th
          name: ภาษาไทย
          build: true
        - locale: zh
          name: 中国人
          build: true
        - locale: ru
          name: Russian
          build: true
        - locale: en
          default: true
          name: English
          build: true
  - print-site:
      add_to_navigation: true
      add_full_urls: false
      add_table_of_contents: true
      toc_title: "Table of Contents"
      toc_depth: 6
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: false
      cover_page_template: "docs/assets/templates/custom_cover_page.tpl"
      path_to_pdf: ""
      include_css: false # dont put true else no toc
      enabled: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
